name: gnn-comparison
channels:
  - pytorch
  - nvidia/label/cuda-11.7.0
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.05.30=h06a4308_0
  - cuda-cccl=11.7.58=hc415cf5_0
  - cuda-command-line-tools=11.7.0=0
  - cuda-compiler=11.7.0=0
  - cuda-cudart=11.7.60=h9538e0e_0
  - cuda-cudart-dev=11.7.60=h6a7c232_0
  - cuda-cuobjdump=11.7.50=h28cc80a_0
  - cuda-cupti=11.7.50=hb6f9eaf_0
  - cuda-cuxxfilt=11.7.50=hb365495_0
  - cuda-documentation=11.7.50=0
  - cuda-driver-dev=11.7.60=0
  - cuda-gdb=11.7.50=h4a0ac72_0
  - cuda-libraries=11.7.0=0
  - cuda-libraries-dev=11.7.0=0
  - cuda-memcheck=11.7.50=hc446b2b_0
  - cuda-nsight=11.7.50=0
  - cuda-nsight-compute=11.7.0=0
  - cuda-nvcc=11.7.64=0
  - cuda-nvdisasm=11.7.50=h5bd0695_0
  - cuda-nvml-dev=11.7.50=h3af1343_0
  - cuda-nvprof=11.7.50=h7a2404d_0
  - cuda-nvprune=11.7.50=h7add7b4_0
  - cuda-nvrtc=11.7.50=hd0285e0_0
  - cuda-nvrtc-dev=11.7.50=heada363_0
  - cuda-nvtx=11.7.50=h05b0816_0
  - cuda-nvvp=11.7.50=hd2289d5_0
  - cuda-sanitizer-api=11.7.50=hb424887_0
  - cuda-toolkit=11.7.0=0
  - cuda-tools=11.7.0=0
  - cuda-visual-tools=11.7.0=0
  - filelock=3.9.0=py310h06a4308_0
  - gds-tools=1.3.0.44=0
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py310heeb90bb_0
  - intel-openmp=2023.1.0=hdb19cb5_46305
  - jinja2=3.1.2=py310h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libcublas=11.10.1.25=he442b6f_0
  - libcublas-dev=11.10.1.25=h0c8ac2b_0
  - libcufft=10.7.2.50=h80a1efe_0
  - libcufft-dev=10.7.2.50=h59a5ac8_0
  - libcufile=1.3.0.44=0
  - libcufile-dev=1.3.0.44=0
  - libcurand=10.2.10.50=heec50f7_0
  - libcurand-dev=10.2.10.50=hd49a9cd_0
  - libcusolver=11.3.5.50=hcab339c_0
  - libcusolver-dev=11.3.5.50=hc6eba6f_0
  - libcusparse=11.7.3.50=h6aaafad_0
  - libcusparse-dev=11.7.3.50=hc644b96_0
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libnpp=11.7.3.21=h3effbd9_0
  - libnpp-dev=11.7.3.21=hb6476a9_0
  - libnvjpeg=11.7.2.34=hfe236c7_0
  - libnvjpeg-dev=11.7.2.34=h2e48410_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - markupsafe=2.1.1=py310h7f8727e_0
  - mkl=2023.1.0=h213fc3f_46343
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py310h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - networkx=3.1=py310h06a4308_0
  - nsight-compute=2022.2.0.13=0
  - openssl=1.1.1v=h7f8727e_0
  - pip=23.2.1=py310h06a4308_0
  - python=3.10.9=h7a1cb2a_2
  - pytorch=2.0.1=py3.10_cpu_0
  - pytorch-mutex=1.0=cpu
  - readline=8.2=h5eee18b_0
  - setuptools=68.0.0=py310h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - sympy=1.11.1=py310h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.12=h1ccaba5_0
  - typing_extensions=4.7.1=py310h06a4308_0
  - tzdata=2023c=h04d1e81_0
  - wheel=0.38.4=py310h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
      - certifi==2023.7.22
      - charset-normalizer==3.2.0
      - idna==3.4
      - joblib==1.3.2
      - numpy==1.25.2
      - psutil==5.9.5
      - pyparsing==3.1.1
      - pyyaml==6.0.1
      - requests==2.31.0
      - scikit-learn==1.3.0
      - scipy==1.11.2
      - threadpoolctl==3.2.0
      - torch-
      - etric==2.3.1
      - tqdm==4.66.1
      - urllib3==2.0.4
